### ISSUE TITLE
Can't find config

### ISSUE THREAD

**Issue by FearOath** [supermassimo/SnowCoated#1]
For some reason after installing the mod and loading the game, the config file for the mod is not loading and I am not able to use the config to allow snow to lay on ice, packed ice, and blue ice blocks. Any way to get it to generate manually?

**Comment by supermassimo** [comment]
There is no config file, these are block tags! they have to be defined under `data/tags/blocks`

**Comment by FearOath** [comment]
Oh I see, sorry. How do I go about changing these? I've never edited block tags before is all

**Comment by supermassimo** [comment]
Of course, just go into your world's folder inside saves, then navigate (or create if they are missing) to the following folder:
`saves/[your world]/data/snowcoated/tags/blocks/`
Once there create the `snow_layer_blacklist.json` file. 
If what you are trying to do is allow snow on ice blocks, then you would write the following on that file:
```json
{
  "replace": true,
  "values": [
    "minecraft:barrier"
  ]
}
```
(This will replace the default blacklist which contains ice, packed ice and barriers, with one that only contains barriers)

**Comment by FearOath** [comment]
> Of course, just go into your world's folder inside saves, then navigate (or create if they are missing) to the following folder: `saves/[your world]/data/snowcoated/tags/blocks/` Once there create the `snow_layer_blacklist.json` file. If what you are trying to do is allow snow on ice blocks, then you would write the following on that file:
> 
> ```json
> {
>   "replace": true,
>   "values": [
>     "minecraft:barrier"
>   ]
> }
> ```
> 
> (This will replace the default blacklist which contains ice, packed ice and barriers, with one that only contains barriers)

So I did this exactly as you've said and it does not work. Not sure whats up here

**Comment by FearOath** [comment]
![filepath](https://github.com/supermassimo/SnowCoated/assets/85411112/09bef68f-5097-4180-9d1f-3f69b30d3fc2)
